import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import { GeometryEditorDialog } from '../GeometryEditorDialog'
import { addCircle, addConstraint, addEllipse, addIntersection, addPoint, addSegment, addArc, createGeometryDocument } from '../../geometry'

describe('GeometryEditorDialog', () => {
  const clickCategoryTool = (category: string, tool: string): void => {
    fireEvent.click(screen.getByRole('button', { name: `${category} ▾` }))
    fireEvent.click(within(screen.getByRole('menu', { name: category })).getByRole('button', { name: tool }))
  }

  it('offers geometry tools and emits SVG on insert', () => {
    const onSave = vi.fn()
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={onSave} />)
    expect(screen.getByRole('button', { name: '点' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '线段' })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '圆' })).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    expect(screen.getByRole('option', { name: '圆' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '文字' }))
    fireEvent.click(screen.getByRole('button', { name: '插入' }))
    expect(onSave).toHaveBeenCalledWith(expect.stringContaining('whizmd-geometry'))
  })

  it('selects a point and deletes it with the keyboard', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.keyDown(canvas, { key: 'Delete' })
    expect(canvas.querySelectorAll('circle')).toHaveLength(0)
  })

  it('creates a parallel constraint by selecting two segments', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    fireEvent.click(canvas, { clientX: 100, clientY: 200 })
    fireEvent.click(canvas, { clientX: 200, clientY: 200 })
    clickCategoryTool('约束', '平行')
    const lines = canvas.querySelectorAll('line')
    fireEvent.click(lines[0])
    fireEvent.click(lines[1])
    expect(screen.getByText('约束', { selector: '.geometry-constraints strong' })).toBeInTheDocument()
  })

  it('offers an endpoint connection tool', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    fireEvent.click(screen.getByRole('button', { name: '构造 ▾' }))
    expect(within(screen.getByRole('menu', { name: '构造' })).getByRole('button', { name: '合并点' })).toBeInTheDocument()
    fireEvent.click(within(screen.getByRole('menu', { name: '构造' })).getByRole('button', { name: '合并点' }))
    expect(screen.getByRole('status')).toHaveTextContent('请选择第一个对象（点）')
  })

  it('connects two selected endpoints', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 200 })
    clickCategoryTool('构造', '合并点')
    const points = canvas.querySelectorAll('circle')
    fireEvent.click(points[0])
    fireEvent.click(points[1])
    expect(canvas.querySelectorAll('circle')).toHaveLength(1)
  })

  it('does not connect the two endpoints of one segment', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    clickCategoryTool('构造', '合并点')
    const points = canvas.querySelectorAll('circle')
    fireEvent.click(points[0])
    fireEvent.click(points[1])
    expect(canvas.querySelectorAll('circle')).toHaveLength(4)
    expect(canvas.querySelectorAll('line')).toHaveLength(1)
    expect(screen.getByRole('status')).toHaveTextContent('同一条线段上的点不能相互连接')
  })

  it('does not create a closed two-edge polygon by connecting endpoints', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 200 })
    fireEvent.click(canvas, { clientX: 150, clientY: 260 })
    clickCategoryTool('构造', '合并点')
    let circles = canvas.querySelectorAll('circle')
    fireEvent.click(circles[1])
    fireEvent.click(circles[4])
    circles = canvas.querySelectorAll('circle')
    expect(canvas.querySelectorAll('line')).toHaveLength(2)
    fireEvent.click(circles[circles.length - 1])
    fireEvent.click(circles[0])
    expect(canvas.querySelectorAll('line')).toHaveLength(2)
    expect(canvas.querySelectorAll('circle')).toHaveLength(7)
    expect(screen.getByRole('status')).toHaveTextContent('闭合二边形')
  })

  it('previews the next polygon edge while drawing', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(canvas, { clientX: 180, clientY: 120 })
    expect(canvas.querySelector('.geometry-preview-line')).not.toBeNull()
  })

  it('starts a segment from an existing endpoint without creating a point', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 300, clientY: 300 })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas.querySelectorAll('circle')[0], { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 400, clientY: 200 })
    expect(canvas.querySelectorAll('line')).toHaveLength(1)
    expect(canvas.querySelectorAll('circle')).toHaveLength(5)
  })

  it('snaps a background click onto a nearby endpoint', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 300, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 104, clientY: 102 })
    fireEvent.click(canvas, { clientX: 200, clientY: 300 })
    const line = canvas.querySelector('line')
    expect(line?.getAttribute('x1')).toBe('100')
    expect(line?.getAttribute('y1')).toBe('100')
    expect(canvas.querySelectorAll('circle')).toHaveLength(5)
  })

  it('applies a horizontal constraint to a clicked segment', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 160 })
    clickCategoryTool('约束', '水平')
    fireEvent.click(canvas, { clientX: 150, clientY: 130 })
    const line = canvas.querySelector('line')
    expect(line?.getAttribute('y1')).toBe(line?.getAttribute('y2'))
  })

  it('renders parallel constraint markers and deletes them on click', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100); document = addPoint(document, 300, 100)
    document = addPoint(document, 100, 200); document = addPoint(document, 300, 200)
    document = addSegment(document, 'P1', 'P2'); document = addSegment(document, 'P3', 'P4')
    document = addConstraint(document, { type: 'parallel', lineA: 'S1', lineB: 'S2' })
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    expect(canvas.querySelectorAll('.geometry-constraint-marker')).toHaveLength(2)
    fireEvent.click(canvas.querySelectorAll('.geometry-constraint-marker')[0])
    expect(canvas.querySelectorAll('.geometry-constraint-marker')).toHaveLength(0)
  })

  it('edits a selected segment length via the inspector', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 300, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    fireEvent.click(canvas.querySelector('line')!)
    const input = screen.getByLabelText('长度')
    fireEvent.change(input, { target: { value: '150' } })
    fireEvent.keyDown(input, { key: 'Enter' })
    const line = canvas.querySelector('line')
    expect(line?.getAttribute('x2')).toBe('250')
  })

  it('draws an arc from center, start, and end clicks', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    fireEvent.click(canvas, { clientX: 200, clientY: 200 })
    fireEvent.click(screen.getByRole('button', { name: '圆弧' }))
    fireEvent.click(canvas.querySelectorAll('circle')[0])
    fireEvent.click(canvas, { clientX: 300, clientY: 200 })
    fireEvent.mouseMove(canvas, { clientX: 300, clientY: 200 })
    expect(canvas.querySelector('.geometry-preview-line')).not.toBeNull()
    fireEvent.mouseMove(canvas, { clientX: 250, clientY: 120 })
    expect(canvas.querySelector('path.geometry-preview-line')).not.toBeNull()
    fireEvent.click(canvas, { clientX: 200, clientY: 300 })
    expect(canvas.querySelector('.geometry-preview-line')).toBeNull()
    expect(canvas.querySelector('path')).not.toBeNull()
  })

  it('materializes a derived intersection via the split tool', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100); document = addPoint(document, 300, 100)
    document = addPoint(document, 200, 50); document = addPoint(document, 200, 250)
    document = addSegment(document, 'P1', 'P2'); document = addSegment(document, 'P3', 'P4')
    document = addIntersection(document, 'S1', 'S2')
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    expect(canvas.querySelectorAll('line')).toHaveLength(2)
    clickCategoryTool('变换', '交点分割')
    fireEvent.click(canvas.querySelector('circle[fill="#cf222e"]')!)
    expect(canvas.querySelectorAll('line')).toHaveLength(4)
    expect(canvas.querySelector('circle[fill="#cf222e"]')).toBeNull()
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('edits arc radius and angles in the inspector', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addArc(document, 'P1', 50, 0, Math.PI / 2)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas.querySelector('path')!)
    const radiusInput = screen.getByLabelText('半径')
    fireEvent.change(radiusInput, { target: { value: '80' } })
    expect(canvas.querySelector('path')?.getAttribute('d')).toContain('80')
    const endInput = screen.getByLabelText('终点角')
    fireEvent.change(endInput, { target: { value: '90' } })
    expect(screen.getByLabelText('终点角')).toHaveValue(90)
  })

  it('adjusts arc angles and radius by dragging handles', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addArc(document, 'P1', 50, 0, Math.PI / 2)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    const handles = canvas.querySelectorAll('circle[r="6"]')
    expect(handles).toHaveLength(3)
    fireEvent.mouseDown(handles[0])
    fireEvent.mouseMove(window, { clientX: 100, clientY: 50 })
    fireEvent.mouseUp(window)
    expect(canvas.querySelector('path')?.getAttribute('d')).toContain('100 50')
    const radiusHandle = canvas.querySelectorAll('circle[r="6"]')[2]
    fireEvent.mouseDown(radiusHandle)
    fireEvent.mouseMove(window, { clientX: 180, clientY: 180 })
    fireEvent.mouseUp(window)
    expect(canvas.querySelector('path')?.getAttribute('d')).not.toContain('A 50')
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('applies tangency by selecting a circle and a segment', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addCircle(document, 'P1', 40)
    document = addPoint(document, 300, 40); document = addPoint(document, 400, 40)
    document = addSegment(document, 'P2', 'P3')
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('约束', '相切')
    expect(screen.getByRole('status')).toHaveTextContent('请选择第一个对象（圆 / 圆弧 / 线段）')
    fireEvent.click(canvas, { clientX: 140, clientY: 100 })
    expect(screen.getByRole('status')).toHaveTextContent('请选择第二个对象')
    fireEvent.click(canvas.querySelector('line')!)
    expect(screen.getByRole('button', { name: '约束 ▾' })).toHaveClass('active')
  })

  it('mirrors the second point across the axis with the symmetry tool', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 150, 150); document = addPoint(document, 280, 150)
    document = addPoint(document, 200, 100); document = addPoint(document, 200, 300)
    document = addSegment(document, 'P3', 'P4')
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('约束', '对称')
    const points = canvas.querySelectorAll('circle[r="5"]')
    fireEvent.click(points[0])
    fireEvent.click(points[1])
    fireEvent.click(canvas.querySelector('line')!)
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(4)
    expect([...canvas.querySelectorAll('circle[r="5"]')].some((circle) => circle.getAttribute('cx') === '250' && circle.getAttribute('cy') === '150')).toBe(true)
    expect(screen.getByRole('button', { name: '约束 ▾' })).toHaveClass('active')
  })

  it('adds a point in the middle of a segment without splitting it', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 300, clientY: 100 })
    clickCategoryTool('构造', '分割线段')
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    expect(canvas.querySelectorAll('line')).toHaveLength(1)
    expect(canvas.querySelectorAll('circle')).toHaveLength(6)
  })

  it('draws and closes a polygon by clicking the first vertex', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    fireEvent.click(canvas, { clientX: 150, clientY: 200 })
    fireEvent.click(canvas.querySelectorAll('circle')[0])
    expect(canvas.querySelectorAll('line')).toHaveLength(3)
  })

  it('undoes an entire polygon with a single undo', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    fireEvent.click(canvas, { clientX: 150, clientY: 200 })
    fireEvent.click(canvas.querySelectorAll('circle')[0])
    expect(canvas.querySelectorAll('line')).toHaveLength(3)
    fireEvent.click(screen.getByRole('button', { name: '撤销' }))
    expect(canvas.querySelectorAll('line')).toHaveLength(0)
    expect(canvas.querySelectorAll('circle')).toHaveLength(0)
    expect(screen.getByRole('button', { name: '撤销' })).toBeDisabled()
  })

  it('keeps draft polygon edges from intercepting clicks', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    const draftLines = canvas.querySelectorAll('line')
    expect(draftLines).toHaveLength(1)
    expect(draftLines[0].getAttribute('pointer-events')).toBe('none')
    expect(canvas.querySelectorAll('circle[r="7"]')).toHaveLength(0)
    fireEvent.click(canvas, { clientX: 150, clientY: 200 })
    expect(canvas.querySelectorAll('line')).toHaveLength(2)
    fireEvent.keyDown(canvas, { key: 'Enter' })
    expect(canvas.querySelectorAll('line')).toHaveLength(3)
    const finalLine = canvas.querySelectorAll('line')[0]
    expect(finalLine.getAttribute('pointer-events')).toBeNull()
    expect(canvas.querySelectorAll('circle[r="7"]')).toHaveLength(6)
  })

  it('draws connected edges while placing polygon vertices', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    expect(canvas.querySelectorAll('line')).toHaveLength(0)
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    expect(canvas.querySelectorAll('line')).toHaveLength(1)
    fireEvent.click(canvas, { clientX: 150, clientY: 200 })
    expect(canvas.querySelectorAll('line')).toHaveLength(2)
    fireEvent.keyDown(canvas, { key: 'Enter' })
    expect(canvas.querySelectorAll('line')).toHaveLength(3)
    fireEvent.click(screen.getByRole('button', { name: '撤销' }))
    expect(canvas.querySelectorAll('line')).toHaveLength(0)
    expect(screen.getByRole('button', { name: '撤销' })).toBeDisabled()
  })

  it('places polygon vertices across pre-existing segments', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 200, clientY: 50 })
    fireEvent.click(canvas, { clientX: 200, clientY: 450 })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 150, clientY: 150 })
    fireEvent.click(canvas, { clientX: 200, clientY: 250 })
    fireEvent.click(canvas, { clientX: 120, clientY: 350 })
    expect(canvas.querySelectorAll('line')).toHaveLength(3)
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(5)
    fireEvent.keyDown(canvas, { key: 'Enter' })
    expect(canvas.querySelectorAll('line')).toHaveLength(4)
  })

  it('cancels a polygon draft without creating history', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    expect(canvas.querySelectorAll('circle')).toHaveLength(1)
    fireEvent.keyDown(canvas, { key: 'Escape' })
    expect(canvas.querySelectorAll('circle')).toHaveLength(0)
    expect(screen.getByRole('button', { name: '撤销' })).toBeDisabled()
  })

  it('does not add a point when a construction tool is active', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('约束', '平行')
    fireEvent.click(canvas, { clientX: 120, clientY: 120 })
    expect(canvas.querySelectorAll('circle')).toHaveLength(0)
  })

  it('blocks polygon vertex drags that would self-cross the shape', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    ;[[100, 100], [500, 100], [500, 500], [100, 500]].forEach(([x, y]) => fireEvent.click(canvas, { clientX: x, clientY: y }))
    fireEvent.click(canvas.querySelectorAll('circle[r="5"]')[0], { clientX: 100, clientY: 100 })
    expect(canvas.querySelectorAll('line')).toHaveLength(4)
    const target = canvas.querySelectorAll('circle[r="5"]')[1]
    fireEvent.mouseDown(target, { clientX: 500, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: -200, clientY: 100 })
    fireEvent.mouseUp(window)
    const dragged = canvas.querySelectorAll('circle[r="5"]')[1]
    expect(Number(dragged.getAttribute('cx'))).toBeGreaterThan(50)
    expect(canvas.querySelectorAll('line')).toHaveLength(4)
  })

  it('keeps drag edits undoable', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    const point = canvas.querySelector('circle')
    fireEvent.mouseDown(point!, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 180, clientY: 180 })
    fireEvent.mouseUp(window)
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('translates a whole segment with the move tool', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100); document = addPoint(document, 300, 100)
    document = addSegment(document, 'P1', 'P2')
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('变换', '移动')
    fireEvent.mouseDown(canvas.querySelector('line')!, { clientX: 200, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 250, clientY: 130 })
    fireEvent.mouseUp(window)
    const line = canvas.querySelector('line')
    expect(line?.getAttribute('x1')).toBe('150')
    expect(line?.getAttribute('y1')).toBe('130')
    expect(line?.getAttribute('x2')).toBe('350')
    expect(line?.getAttribute('y2')).toBe('130')
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('moves a circle by dragging its stroke with the move tool', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addCircle(document, 'P1', 40)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('变换', '移动')
    fireEvent.mouseDown(canvas.querySelector('circle[r="40"]')!, { clientX: 140, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 160, clientY: 110 })
    fireEvent.mouseUp(window)
    const center = [...canvas.querySelectorAll('circle[r="5"]')][0]
    expect(center.getAttribute('cx')).toBe('120')
    expect(center.getAttribute('cy')).toBe('110')
  })

  it('creates a midpoint from two selected points', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('构造', '中点')
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '插入' }))
    expect(screen.queryByRole('img', { name: '几何图画布' })).toBeInTheDocument()
  })

  it('adjusts the selected circle radius with arrow keys', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    fireEvent.click(screen.getByRole('option', { name: '圆' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 180, clientY: 100 })
    fireEvent.mouseUp(canvas, { clientX: 180, clientY: 100 })
    const circle = canvas.querySelector('circle[r="40"]')
    expect(circle).not.toBeNull()
    fireEvent.click(circle!)
    fireEvent.keyDown(canvas, { key: 'ArrowUp' })
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('does not create a second circle when dragging the radius handle', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addCircle(document, 'P1', 40)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    const handle = canvas.querySelector('circle[data-handle][r="6"]')
    expect(handle).not.toBeNull()
    const circleCount = () => canvas.querySelectorAll('circle:not([data-handle]):not([r="5"]):not(.geometry-snap-halo)').length
    expect(circleCount()).toBe(1)
    fireEvent.mouseDown(handle!, { clientX: 140, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 160, clientY: 120 })
    fireEvent.mouseUp(window)
    fireEvent.click(handle!, { clientX: 160, clientY: 120 })
    expect(circleCount()).toBe(1)
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(1)
  })

  it('keeps drag edits undoable', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    const point = canvas.querySelector('circle')
    fireEvent.mouseDown(point!, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 180, clientY: 180 })
    fireEvent.mouseUp(window)
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('draws a square by dragging with the shape tool', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 260 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 260 })
    expect(canvas.querySelectorAll('line:not(.geometry-constraint-marker)')).toHaveLength(4)
    const constraintLabels = [...document.querySelectorAll('.geometry-constraints span')].map((element) => element.textContent ?? '')
    expect(constraintLabels.some((label) => label.includes('平行'))).toBe(true)
    expect(constraintLabels.some((label) => label.includes('等长'))).toBe(true)
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('does not start a new shape when pressing near an existing shape', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 160 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 160 })
    expect(canvas.querySelectorAll('line:not(.geometry-constraint-marker)')).toHaveLength(4)
    fireEvent.mouseDown(canvas, { clientX: 306, clientY: 306 })
    fireEvent.mouseMove(window, { clientX: 380, clientY: 380 })
    fireEvent.mouseUp(window)
    expect(canvas.querySelectorAll('line:not(.geometry-constraint-marker)')).toHaveLength(4)
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(4)
  })

  it('scales a shape rigidly when dragging its vertex and leaves other shapes untouched', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 160 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 160 })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    ;[[420, 120], [520, 120], [470, 220]].forEach(([x, y]) => fireEvent.click(canvas, { clientX: x, clientY: y }))
    fireEvent.click(canvas, { clientX: 420, clientY: 120 })
    const before = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => ({ cx: circle.getAttribute('cx'), cy: circle.getAttribute('cy') }))
    expect(before).toHaveLength(7)
    fireEvent.mouseDown(canvas.querySelectorAll('circle[r="5"]')[0], { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 60, clientY: 60 })
    fireEvent.mouseUp(window)
    const after = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => ({ cx: circle.getAttribute('cx'), cy: circle.getAttribute('cy') }))
    expect(after[0]).toEqual({ cx: '60', cy: '60' })
    expect(after[1]).toEqual({ cx: '300', cy: '60' })
    expect(after[2]).toEqual({ cx: '300', cy: '300' })
    expect(after[3]).toEqual({ cx: '60', cy: '300' })
    expect(after.slice(4)).toEqual(before.slice(4))
    fireEvent.click(screen.getByRole('button', { name: '撤销' }))
    const restored = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => ({ cx: circle.getAttribute('cx'), cy: circle.getAttribute('cy') }))
    expect(restored).toEqual(before)
  })

  it('rotates a shape rigidly with the rotate tool and leaves other shapes untouched', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 160 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 160 })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    ;[[420, 120], [520, 120], [470, 220]].forEach(([x, y]) => fireEvent.click(canvas, { clientX: x, clientY: y }))
    fireEvent.click(canvas, { clientX: 420, clientY: 120 })
    const before = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => ({ cx: circle.getAttribute('cx'), cy: circle.getAttribute('cy') }))
    expect(before).toHaveLength(7)
    clickCategoryTool('变换', '旋转')
    fireEvent.mouseDown(canvas.querySelectorAll('circle[r="5"]')[1], { clientX: 300, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 100, clientY: 200 })
    fireEvent.mouseUp(window)
    const after = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => ({ cx: Number(circle.getAttribute('cx')), cy: Number(circle.getAttribute('cy')) }))
    const square = after.slice(0, 4)
    const side = (a: { cx: number; cy: number }, b: { cx: number; cy: number }): number => Math.hypot(a.cx - b.cx, a.cy - b.cy)
    for (const [i, j] of [[0, 1], [1, 2], [2, 3], [3, 0]]) {
      expect(side(square[i!], square[j!])).toBeCloseTo(200, 3)
    }
    expect(side(square[0], square[2])).toBeCloseTo(Math.hypot(200, 200), 3)
    const centroid = {
      x: square.reduce((sum, point) => sum + point.cx, 0) / 4,
      y: square.reduce((sum, point) => sum + point.cy, 0) / 4
    }
    expect(centroid.x).toBeCloseTo(200, 3)
    expect(centroid.y).toBeCloseTo(200, 3)
    expect(after.slice(4).map((point) => ({ cx: String(point.cx), cy: String(point.cy) }))).toEqual(before.slice(4))
    fireEvent.click(screen.getByRole('button', { name: '撤销' }))
    const restored = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => ({ cx: circle.getAttribute('cx'), cy: circle.getAttribute('cy') }))
    expect(restored).toEqual(before)
  })

  it('rotates when grabbing the middle of an edge with the rotate tool', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 160 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 160 })
    clickCategoryTool('变换', '旋转')
    const edge = canvas.querySelectorAll('line:not(.geometry-constraint-marker)')[0]
    fireEvent.mouseDown(edge!, { clientX: 200, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 120, clientY: 200 })
    fireEvent.mouseUp(window)
    const after = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => ({ cx: Number(circle.getAttribute('cx')), cy: Number(circle.getAttribute('cy')) }))
    const square = after.slice(0, 4)
    const side = (a: { cx: number; cy: number }, b: { cx: number; cy: number }): number => Math.hypot(a.cx - b.cx, a.cy - b.cy)
    for (const [i, j] of [[0, 1], [1, 2], [2, 3], [3, 0]]) {
      expect(side(square[i!], square[j!])).toBeCloseTo(200, 3)
    }
    // −90° 刚体旋转：四个顶点恰好落在原顶点集合上（正方形自映射）。
    for (const point of square) {
      expect([[100, 100], [300, 100], [300, 300], [100, 300]].some(([x, y]) => Math.hypot(point.cx - x, point.cy - y) < 1e-6)).toBe(true)
    }
  })

  it('rotates instead of scaling when pressing the endpoint handle under the rotate tool', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 160 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 160 })
    clickCategoryTool('变换', '旋转')
    const anchorBeforeX = Number(canvas.querySelectorAll('circle[r="5"]')[2].getAttribute('cx'))
    const anchorBeforeY = Number(canvas.querySelectorAll('circle[r="5"]')[2].getAttribute('cy'))
    expect([anchorBeforeX, anchorBeforeY]).toEqual([300, 300]) // 对角点 P3：缩放模式下保持不动
    fireEvent.mouseDown(canvas.querySelector('circle[data-handle][r="7"]')!, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 95, clientY: 105 })
    fireEvent.mouseUp(window)
    const anchorAfter = canvas.querySelectorAll('circle[r="5"]')[2]
    const moved = Math.hypot(
      Number(anchorAfter.getAttribute('cx')) - anchorBeforeX,
      Number(anchorAfter.getAttribute('cy')) - anchorBeforeY
    )
    expect(moved).toBeGreaterThan(2)
    const p1 = canvas.querySelectorAll('circle[r="5"]')[0]
    expect(Math.hypot(Number(p1.getAttribute('cx')) - 95, Number(p1.getAttribute('cy')) - 105)).toBeLessThan(0.5)
  })

  it('moves a whole rectangle when dragging one of its edges with the move tool', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    fireEvent.click(screen.getByRole('option', { name: '矩形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 180 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 180 })
    clickCategoryTool('变换', '移动')
    const edge = canvas.querySelectorAll('line:not(.geometry-constraint-marker)')[0]
    fireEvent.mouseDown(edge!, { clientX: 200, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 230, clientY: 120 })
    fireEvent.mouseUp(window)
    const points = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => ({ cx: Number(circle.getAttribute('cx')), cy: Number(circle.getAttribute('cy')) }))
    expect(points).toEqual([
      { cx: 130, cy: 120 },
      { cx: 330, cy: 120 },
      { cx: 330, cy: 200 },
      { cx: 130, cy: 200 }
    ])
  })

  it('stretches a rectangle freely from its corner without keeping aspect ratio', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    fireEvent.click(screen.getByRole('option', { name: '矩形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 180 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 180 })
    fireEvent.mouseDown(canvas.querySelectorAll('circle[r="5"]')[0], { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 150, clientY: 100 })
    fireEvent.mouseUp(window)
    const points = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => ({ cx: Number(circle.getAttribute('cx')), cy: Number(circle.getAttribute('cy')) }))
    // 对角点固定，宽度跟随光标，高度保持不变。
    expect(points[0]).toEqual({ cx: 150, cy: 100 })
    expect(points[1]).toEqual({ cx: 300, cy: 100 })
    expect(points[2]).toEqual({ cx: 300, cy: 180 })
    expect(points[3]).toEqual({ cx: 150, cy: 180 })
  })

  it('edits the interior angle of a parallelogram vertex from the side panel', async () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    fireEvent.click(screen.getByRole('option', { name: '平行四边形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 300 })
    fireEvent.mouseMove(window, { clientX: 400, clientY: 200 })
    fireEvent.mouseUp(canvas, { clientX: 400, clientY: 200 })
    const vertices = canvas.querySelectorAll('circle[r="5"]')
    const p2 = vertices[1]
    const px = Number(p2.getAttribute('cx'))
    const py = Number(p2.getAttribute('cy'))
    fireEvent.mouseDown(p2, { clientX: px, clientY: py })
    fireEvent.mouseUp(window)
    const input = await screen.findByLabelText('内角')
    expect(Number((input as HTMLInputElement).value)).toBeGreaterThan(90)
    const before = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => `${circle.getAttribute('cx')},${circle.getAttribute('cy')}`)
    fireEvent.change(input, { target: { value: '95' } })
    fireEvent.keyDown(input, { key: 'Enter' })
    await waitFor(() => {
      expect(document.querySelector('.geometry-constraints')?.textContent).toContain('角度')
    })
    const after = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => `${circle.getAttribute('cx')},${circle.getAttribute('cy')}`)
    expect(after).not.toEqual(before)
  })

  it('selects any segment with the point tool and shows its editable length', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 160 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 160 })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    const edge = canvas.querySelectorAll('line:not(.geometry-constraint-marker)')[0]
    fireEvent.click(edge!, { clientX: 200, clientY: 100 })
    expect(screen.getByText('类型: segment')).toBeInTheDocument()
    expect(screen.getByLabelText('长度')).not.toBeNull()
    // 点击边不再穿透创建新点
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(4)
  })

  it('edits circle radius from the selected center point', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addCircle(document, 'P1', 40)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.mouseDown(canvas.querySelector('circle[r="5"]')!, { clientX: 100, clientY: 100 })
    fireEvent.mouseUp(window)
    const radiusInput = screen.getByLabelText('半径')
    fireEvent.change(radiusInput, { target: { value: '60' } })
    expect(canvas.querySelector('circle[r="60"]')).not.toBeNull()
  })

  it('keeps a ring point on the circumference when editing the radius from it', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addCircle(document, 'P1', 40)
    document = addPoint(document, 140, 100)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    const ringPoint = [...canvas.querySelectorAll('circle[r="5"]')][1]
    fireEvent.mouseDown(ringPoint, { clientX: 140, clientY: 100 })
    fireEvent.mouseUp(window)
    const radiusInput = screen.getByLabelText('半径')
    fireEvent.change(radiusInput, { target: { value: '80' } })
    expect(canvas.querySelector('circle[r="80"]')).not.toBeNull()
    const moved = [...canvas.querySelectorAll('circle[r="5"]')][1]
    expect(moved.getAttribute('cx')).toBe('180')
    expect(moved.getAttribute('cy')).toBe('100')
  })

  it('shows an editable interior angle for free triangle vertices', async () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    ;[[150, 150], [350, 150], [250, 320]].forEach(([x, y]) => fireEvent.click(canvas, { clientX: x, clientY: y }))
    fireEvent.click(canvas, { clientX: 150, clientY: 150 })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    const vertex = canvas.querySelectorAll('circle[r="5"]')[0]
    fireEvent.mouseDown(vertex, { clientX: 150, clientY: 150 })
    fireEvent.mouseUp(window)
    const input = await screen.findByLabelText('内角')
    expect(Number((input as HTMLInputElement).value)).toBeGreaterThan(30)
    const before = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => `${circle.getAttribute('cx')},${circle.getAttribute('cy')}`)
    fireEvent.change(input, { target: { value: '80' } })
    fireEvent.keyDown(input, { key: 'Enter' })
    await waitFor(() => {
      const after = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => `${circle.getAttribute('cx')},${circle.getAttribute('cy')}`)
      expect(after).not.toEqual(before)
    })
  })

  it('shows rectangle corner angles as read-only 90 degrees', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    fireEvent.click(screen.getByRole('option', { name: '矩形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 180 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 180 })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    const vertex = canvas.querySelectorAll('circle[r="5"]')[0]
    fireEvent.mouseDown(vertex, { clientX: 100, clientY: 100 })
    fireEvent.mouseUp(window)
    expect(screen.getByText(/内角: 90°/)).toBeInTheDocument()
    expect(screen.queryByLabelText('内角')).toBeNull()
  })

  it('shows editable point coordinates in the inspector', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    expect(screen.getByLabelText('X')).toHaveValue(100)
    fireEvent.change(screen.getByLabelText('X'), { target: { value: '140' } })
    expect(screen.getByLabelText('X')).toHaveValue(140)
  })

  it('creates an angle constraint from three points and edits its value', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    ;[[200, 200], [300, 200], [350, 150]].forEach(([x, y]) => fireEvent.click(canvas, { clientX: x, clientY: y }))
    clickCategoryTool('约束', '角度')
    const points = [...canvas.querySelectorAll('circle[r="5"]')]
    fireEvent.click(points[0])
    fireEvent.click(points[1])
    fireEvent.click(points[2])
    expect(screen.getByText(/角度/, { selector: '.geometry-constraints span' })).toBeInTheDocument()
    const input = screen.getByLabelText('角度-0')
    expect(input).toHaveValue(135)
    fireEvent.change(input, { target: { value: '90' } })
    const armB = [...canvas.querySelectorAll('circle[r="5"]')][2]
    expect(Number(armB.getAttribute('cx'))).toBeCloseTo(300, 5)
    expect(Number(armB.getAttribute('cy'))).toBeCloseTo(200 - Math.hypot(50, 50), 5)
  })

  it('renames a selected point and shows the label on canvas', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.change(screen.getByLabelText('名称'), { target: { value: 'A' } })
    expect(screen.getByLabelText('名称')).toHaveValue('A')
    expect(canvas.textContent).toContain('A')
    expect(screen.getAllByText('A').length).toBeGreaterThan(0)
  })

  it('selects points inside a dragged rectangle', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 200 })
    fireEvent.mouseDown(canvas, { clientX: 70, clientY: 70 })
    fireEvent.mouseMove(window, { clientX: 230, clientY: 230 })
    fireEvent.mouseUp(window)
    expect(screen.getByText('2 个对象')).toBeInTheDocument()
  })

  it('creates an ellipse by selecting two foci and dragging from the second focus', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '形状' }))
    fireEvent.click(screen.getByRole('option', { name: '椭圆' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 200 })
    fireEvent.click(canvas, { clientX: 200, clientY: 200 })
    const focus = canvas.querySelectorAll('circle[r="5"]')[1]
    fireEvent.mouseDown(focus, { clientX: 200, clientY: 200 })
    fireEvent.mouseMove(window, { clientX: 200, clientY: 350 })
    fireEvent.mouseUp(window)
    const ellipse = canvas.querySelector('ellipse:not(.geometry-preview-line)')
    expect(ellipse).not.toBeNull()
    expect(Number(ellipse!.getAttribute('rx'))).toBeGreaterThan(100)
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(2)
  })

  it('shows ellipse properties when the ellipse is selected', () => {
    let document = addPoint(createGeometryDocument(), 100, 200)
    document = addPoint(document, 200, 200)
    document = addEllipse(document, 'P1', 'P2', 140)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas.querySelector('ellipse')!)
    expect(screen.getByText('类型: ellipse')).toBeInTheDocument()
    expect(screen.getByLabelText('半长轴')).toHaveValue(140)
    fireEvent.change(screen.getByLabelText('半长轴'), { target: { value: '160' } })
    expect(canvas.querySelector('ellipse')).toHaveAttribute('rx', '160')
  })
})
