import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import { GeometryEditorDialog } from '../GeometryEditorDialog'
import { addCircle, addConstraint, addEllipse, addPoint, addSegment, addArc, createGeometryDocument } from '../../geometry'

describe('GeometryEditorDialog', () => {
  const clickCategoryTool = (category: string, tool: string): void => {
    fireEvent.click(screen.getByRole('button', { name: `${category} ▾` }))
    fireEvent.click(within(screen.getByRole('menu', { name: category })).getByRole('button', { name: tool }))
  }

  it('shows vector drawing tools and separate selection and move modes', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    expect(screen.getByRole('complementary', { name: '绘制' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '选择' }).querySelector('svg')).not.toBeNull()
    expect(screen.getByRole('button', { name: '移动' }).querySelector('svg')).not.toBeNull()
    expect(screen.getByRole('button', { name: '撤销' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '重做' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '点' }).querySelector('circle')).not.toBeNull()
    expect(screen.getByRole('button', { name: '线段' }).querySelector('path')).not.toBeNull()
    expect(screen.getByRole('button', { name: '圆弧' }).querySelector('path')).not.toBeNull()
    expect(screen.getByRole('option', { name: '圆' }).querySelector('circle')).not.toBeNull()
    expect(screen.getByRole('option', { name: '椭圆' }).querySelector('ellipse')).not.toBeNull()
    expect(screen.getByRole('option', { name: '矩形' }).querySelector('rect')).not.toBeNull()
  })

  it('moves a point with the hand mode', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '移动' }))
    const point = canvas.querySelector('circle[r="5"]')!
    fireEvent.mouseDown(point, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 140, clientY: 130 })
    fireEvent.mouseUp(window)
    expect(point.getAttribute('cx')).toBe('140')
    expect(point.getAttribute('cy')).toBe('130')
  })

  it('offers geometry tools and emits SVG on insert', () => {
    const onSave = vi.fn()
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={onSave} />)
    expect(screen.getByRole('button', { name: '点' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '线段' })).toBeInTheDocument()
    expect(screen.getByRole('option', { name: '圆' })).toBeInTheDocument()
    expect(screen.getByRole('option', { name: '圆' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '文字' }))
    fireEvent.click(screen.getByRole('button', { name: '插入' }))
    expect(onSave).toHaveBeenCalledWith(expect.stringContaining('whizmd-geometry'))
  })

  it('uses save semantics when editing an existing geometry', () => {
    const onSave = vi.fn()
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={onSave} existingPath="assets/geometry.svg" />)
    expect(screen.getByRole('button', { name: '保存' })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '插入' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '保存' }))
    expect(onSave).toHaveBeenCalledWith(expect.stringContaining('whizmd-geometry'))
  })

  it('cancels without saving or inserting an image', () => {
    const onSave = vi.fn()
    const onClose = vi.fn()
    render(<GeometryEditorDialog onClose={onClose} onSave={onSave} />)
    fireEvent.click(screen.getByRole('button', { name: '取消' }))
    expect(onClose).toHaveBeenCalledOnce()
    expect(onSave).not.toHaveBeenCalled()
  })

  it('creates text after confirming the text prompt', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '文字' }))
    fireEvent.click(canvas, { clientX: 120, clientY: 140 })
    fireEvent.change(screen.getByRole('textbox'), { target: { value: '说明文字' } })
    fireEvent.keyDown(screen.getByRole('textbox'), { key: 'Enter' })
    expect(canvas.textContent).toContain('说明文字')
    expect(screen.getByRole('button', { name: '选择' })).toHaveClass('active')
  })

  it('keeps focus in the inline text editor while typing Chinese', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '文字' }))
    fireEvent.click(canvas, { clientX: 120, clientY: 140 })
    const input = screen.getByRole('textbox')
    fireEvent.change(input, { target: { value: '中' } })
    expect(document.activeElement).toBe(input)
    fireEvent.change(input, { target: { value: '中文' } })
    expect(document.activeElement).toBe(input)
    fireEvent.keyDown(input, { key: 'Enter', keyCode: 229, isComposing: true })
    expect(screen.getByRole('textbox')).toBeInTheDocument()
    expect(document.activeElement).toBe(input)
  })

  it('moves and styles a selected text annotation', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '文字' }))
    fireEvent.click(canvas, { clientX: 120, clientY: 140 })
    fireEvent.change(screen.getByRole('textbox'), { target: { value: '标注' } })
    fireEvent.keyDown(screen.getByRole('textbox'), { key: 'Enter' })
    const text = canvas.querySelector('text:not([pointer-events="none"])')!
    fireEvent.mouseDown(text, { clientX: 120, clientY: 140 })
    fireEvent.mouseMove(window, { clientX: 150, clientY: 170 })
    fireEvent.mouseUp(window)
    fireEvent.change(screen.getByLabelText('字号'), { target: { value: '20' } })
    fireEvent.change(screen.getByLabelText('文字颜色'), { target: { value: '#ff0000' } })
    fireEvent.change(screen.getByLabelText('文字旋转'), { target: { value: '45' } })
    expect(screen.getByLabelText('字号')).toHaveValue(20)
    expect(screen.getByLabelText('文字颜色')).toHaveValue('#ff0000')
    expect(screen.getByLabelText('文字旋转')).toHaveValue(45)
  })

  it('anchors a text annotation to a segment', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 200, 100)
    document = addSegment(document, 'P1', 'P2')
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '文字' }))
    fireEvent.click(canvas, { clientX: 150, clientY: 120 })
    fireEvent.change(screen.getByRole('textbox'), { target: { value: '在线段' } })
    fireEvent.keyDown(screen.getByRole('textbox'), { key: 'Enter' })
    fireEvent.click(canvas.querySelector('text')!)
    fireEvent.change(screen.getByLabelText('锚定线段'), { target: { value: 'S1' } })
    expect(screen.getByLabelText('锚定线段')).toHaveValue('S1')
  })

  it('opens the text prompt when clicking over an existing point', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 120, 140)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '文字' }))
    fireEvent.click(canvas.querySelector('circle[r="5"]')!, { clientX: 120, clientY: 140 })
    fireEvent.change(screen.getByRole('textbox'), { target: { value: '点注释' } })
    fireEvent.keyDown(screen.getByRole('textbox'), { key: 'Enter' })
    expect(canvas.textContent).toContain('点注释')
  })

  it('cancels an active polygon draft without closing the dialog on Escape', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.keyDown(document, { key: 'Escape' })
    expect(screen.getByRole('dialog')).toBeInTheDocument()
    expect(canvas.querySelectorAll('circle')).toHaveLength(0)
  })

  it('selects a point and deletes it with the keyboard', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.keyDown(canvas, { key: 'Delete' })
    expect(canvas.querySelectorAll('circle')).toHaveLength(0)
  })

  it('selects a line with the first-level select tool and shows its properties', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 200, 100)
    document = addSegment(document, 'P1', 'P2')
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} initialTool="select" />)
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas.querySelector('line')!)
    expect(screen.getByText('类型: segment')).toBeInTheDocument()
    expect(screen.getByLabelText('长度')).toHaveValue(2.5)
    expect(screen.getByRole('button', { name: '选择' })).toHaveClass('active')
  })

  it('drags a selected line as one object', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 200, 100)
    document = addSegment(document, 'P1', 'P2')
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} initialTool="move" />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    const line = canvas.querySelector('line')!
    fireEvent.mouseDown(line, { clientX: 150, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 180, clientY: 130 })
    fireEvent.mouseUp(window)
    expect([...canvas.querySelectorAll('circle[r="5"]')].map((circle) => [circle.getAttribute('cx'), circle.getAttribute('cy')])).toEqual([['130', '130'], ['230', '130']])
  })

  it('creates a parallel constraint by selecting two segments', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 200 })
    fireEvent.click(canvas, { clientX: 200, clientY: 200 })
    clickCategoryTool('约束', '平行')
    const lines = canvas.querySelectorAll('line')
    fireEvent.click(lines[0])
    fireEvent.click(lines[1])
    fireEvent.click(screen.getByRole('button', { name: '移动' }))
    fireEvent.click(canvas.querySelectorAll('line:not(.geometry-constraint-marker)')[0])
    expect(screen.getByText('约束', { selector: '.geometry-constraints strong' })).toBeInTheDocument()
  })

  it('shows the referenced edges in a constraint detail', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 200, 100)
    document = addPoint(document, 100, 200)
    document = addPoint(document, 200, 200)
    document = addSegment(document, 'P1', 'P2')
    document = addSegment(document, 'P3', 'P4')
    document = addConstraint(document, { type: 'parallel', lineA: 'S1', lineB: 'S2' })
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
     fireEvent.click(screen.getByRole('button', { name: '移动' }))
    fireEvent.click(canvas.querySelectorAll('line:not(.geometry-constraint-marker)')[0])
    expect(screen.getByText(/P1-P2 \/ P3-P4/)).toBeInTheDocument()
  })

  it('displays the absolute value of a negative fixed angle', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 200, 100)
    document = addPoint(document, 100, 200)
    document = addConstraint(document, { type: 'fixedAngle', a: 'P2', vertex: 'P1', b: 'P3', value: -Math.PI / 2 })
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas.querySelectorAll('circle[r="5"]')[0])
    expect(screen.getByText(/∠P2P1P3 = 90°/)).toBeInTheDocument()
    expect(screen.getByLabelText('角度-0')).toHaveValue(90)
  })

  it('offers an endpoint connection tool', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    fireEvent.click(screen.getByRole('button', { name: '构造 ▾' }))
    expect(within(screen.getByRole('menu', { name: '构造' })).getByRole('button', { name: '合并点' })).toBeInTheDocument()
    fireEvent.click(within(screen.getByRole('menu', { name: '构造' })).getByRole('button', { name: '合并点' }))
    expect(screen.getByRole('status')).toHaveTextContent('请选择第一个对象（点）')
  })

  it('splits a selected node connection into a new coincident point', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 200, 100)
    document = addPoint(document, 100, 200)
    document = addSegment(document, 'P1', 'P2')
    document = addSegment(document, 'P1', 'P3')
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('构造', '拆分节点')
    fireEvent.click(canvas.querySelectorAll('circle[r="5"]')[0])
    fireEvent.click(canvas.querySelectorAll('line')[1])
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(4)
    expect(screen.getByRole('button', { name: '选择' })).toHaveClass('active')
  })

  it('connects two selected endpoints', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    fireEvent.click(canvas, { clientX: 200, clientY: 200 })
    clickCategoryTool('构造', '合并点')
    const points = canvas.querySelectorAll('circle')
    fireEvent.click(points[0])
    fireEvent.click(points[1])
    expect(canvas.querySelectorAll('circle')).toHaveLength(1)
  })

  it('allows merging an anchored arc endpoint without removing the arc', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 150, 100)
    document = addArc(document, 'P1', 50, 0, Math.PI / 2, { startAnchor: 'P2' })
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('构造', '合并点')
    const arcStartHandle = canvas.querySelectorAll('circle[r="6"]')[0]
    fireEvent.mouseDown(arcStartHandle)
    fireEvent.click(canvas.querySelectorAll('circle[r="5"]')[0])
    expect(canvas.querySelector('path')).not.toBeNull()
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(1)
  })

  it('shares a line endpoint with an arc endpoint after connecting them', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 150, 100)
    document = addPoint(document, 200, 100)
    document = addSegment(document, 'P1', 'P2')
    document = addArc(document, 'P1', 50, 0, Math.PI / 2, { startAnchor: 'P3' })
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('构造', '合并点')
    const points = [...canvas.querySelectorAll('circle[r="5"]')]
    fireEvent.click(points[1])
    fireEvent.click(points[2])
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(2)
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    fireEvent.mouseDown(canvas.querySelector('circle[r="5"]')!, { clientX: 150, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 180, clientY: 130 })
    fireEvent.mouseUp(window)
    expect(canvas.querySelector('path:not(.geometry-hit-area)')?.getAttribute('d')).toContain('180')
  })

  it('keeps a shared arc endpoint on the arc while dragging it', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 150, 100)
    document = addPoint(document, 200, 100)
    document = addSegment(document, 'P1', 'P2')
    document = addArc(document, 'P1', 50, 0, Math.PI / 2, { startAnchor: 'P3' })
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('构造', '合并点')
    const points = [...canvas.querySelectorAll('circle[r="5"]')]
    fireEvent.click(points[1])
    fireEvent.click(points[2])
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    const shared = [...canvas.querySelectorAll('circle[r="5"]')].find((point) => point.getAttribute('cx') === '150')!
    fireEvent.mouseDown(shared, { clientX: 150, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 100, clientY: 50 })
    fireEvent.mouseUp(window)
    const moved = [...canvas.querySelectorAll('circle[r="5"]')].find((point) => point.getAttribute('cx') === '100' && point.getAttribute('cy') === '50')!
    expect(moved).not.toBeUndefined()
    expect(canvas.querySelector('path:not(.geometry-hit-area)')?.getAttribute('d')).toContain('100 50')
  })

  it('moves an existing anchored arc endpoint instead of leaving a duplicate point', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 150, 100)
    document = addArc(document, 'P1', 50, 0, Math.PI / 2, { startAnchor: 'P2' })
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    const startHandle = canvas.querySelectorAll('circle[r="6"]')[0]
    fireEvent.mouseDown(startHandle, { clientX: 150, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 100, clientY: 50 })
    fireEvent.mouseUp(window)
    const points = [...canvas.querySelectorAll('circle[r="5"]')]
    expect(points).toHaveLength(2)
    expect(points.some((point) => point.getAttribute('cx') === '100' && point.getAttribute('cy') === '50')).toBe(true)
    expect(canvas.querySelector('path')?.getAttribute('d')).toContain('100 50')
  })

  it('does not connect the two endpoints of one segment', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    clickCategoryTool('构造', '合并点')
    const points = canvas.querySelectorAll('circle')
    fireEvent.click(points[0])
    fireEvent.click(points[1])
    expect(canvas.querySelectorAll('circle')).toHaveLength(4)
    expect(canvas.querySelectorAll('line')).toHaveLength(1)
    expect(screen.getByRole('status')).toHaveTextContent('同一条线段的两个端点不能相互连接')
  })

  it('does not create a closed two-edge polygon by connecting endpoints', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 200, clientY: 200 })
    fireEvent.click(canvas, { clientX: 150, clientY: 260 })
    clickCategoryTool('构造', '合并点')
    let circles = canvas.querySelectorAll('circle')
    fireEvent.click(circles[1])
    fireEvent.click(circles[4])
    circles = canvas.querySelectorAll('circle')
    expect(canvas.querySelectorAll('line')).toHaveLength(2)
    fireEvent.click(circles[circles.length - 1])
    fireEvent.click(circles[0])
    expect(canvas.querySelectorAll('line')).toHaveLength(2)
    expect(canvas.querySelectorAll('circle')).toHaveLength(7)
    expect(canvas.querySelectorAll('line')).toHaveLength(2)
  })

  it('keeps a constrained rectangle unchanged when connecting an external endpoint to its vertex', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100); document = addPoint(document, 300, 100); document = addPoint(document, 300, 300); document = addPoint(document, 100, 300)
    document = addPoint(document, 100, 100); document = addPoint(document, 40, 40)
    document = addSegment(document, 'P1', 'P2'); document = addSegment(document, 'P2', 'P3'); document = addSegment(document, 'P3', 'P4'); document = addSegment(document, 'P4', 'P1'); document = addSegment(document, 'P5', 'P6')
    document = addConstraint(document, { type: 'perpendicular', lineA: 'S1', lineB: 'S2' }); document = addConstraint(document, { type: 'parallel', lineA: 'S1', lineB: 'S3' }); document = addConstraint(document, { type: 'parallel', lineA: 'S2', lineB: 'S4' })
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('构造', '合并点')
    const points = canvas.querySelectorAll('circle[r="5"]')
    fireEvent.click(points[4]); fireEvent.click(points[0])
    expect([...canvas.querySelectorAll('circle[r="5"]')].slice(0, 4).map((point) => [point.getAttribute('cx'), point.getAttribute('cy')])).toEqual([['100', '100'], ['300', '100'], ['300', '300'], ['100', '300']])
  })

  it('previews the next polygon edge while drawing', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(canvas, { clientX: 180, clientY: 120 })
    expect(canvas.querySelector('.geometry-preview-line')).not.toBeNull()
  })

  it('starts a segment from an existing endpoint without creating a point', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    fireEvent.click(canvas, { clientX: 300, clientY: 300 })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.mouseDown(canvas.querySelectorAll('circle')[0], { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 400, clientY: 200 })
    fireEvent.mouseUp(canvas, { clientX: 400, clientY: 200 })
    expect(canvas.querySelectorAll('line')).toHaveLength(1)
    expect(canvas.querySelectorAll('circle')).toHaveLength(5)
    expect(screen.getByRole('button', { name: '选择' })).toHaveClass('active')
  })

  it('does not create a point when a segment drag is released at its start', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseUp(canvas, { clientX: 100, clientY: 100 })
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(0)
    expect(canvas.querySelectorAll('line:not(.geometry-constraint-marker)')).toHaveLength(0)
    expect(screen.getByRole('button', { name: '选择' })).toHaveClass('active')
  })

  it('does not drag a constrained shape when drawing a segment from its vertex', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('option', { name: '正方形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 300 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 300 })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    const vertex = canvas.querySelectorAll('circle[r="5"]')[0]
    fireEvent.mouseDown(vertex, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 60, clientY: 60 })
    fireEvent.mouseUp(canvas, { clientX: 60, clientY: 60 })
    const points = [...canvas.querySelectorAll('circle[r="5"]')].map((point) => [point.getAttribute('cx'), point.getAttribute('cy')])
    expect(points.slice(0, 4)).toEqual([['100', '100'], ['300', '100'], ['300', '300'], ['100', '300']])
    expect(canvas.querySelectorAll('line:not(.geometry-constraint-marker)')).toHaveLength(5)
  })

  it('snaps a background click onto a nearby endpoint', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    fireEvent.click(canvas, { clientX: 300, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 104, clientY: 102 })
    fireEvent.click(canvas, { clientX: 200, clientY: 300 })
    const line = canvas.querySelector('line')
    expect(line?.getAttribute('x1')).toBe('100')
    expect(line?.getAttribute('y1')).toBe('100')
    expect(canvas.querySelectorAll('circle')).toHaveLength(5)
  })

  it('applies a horizontal constraint to a clicked segment', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 160 })
    clickCategoryTool('约束', '水平')
    fireEvent.click(canvas, { clientX: 150, clientY: 130 })
    const line = canvas.querySelector('line')
    expect(line?.getAttribute('y1')).toBe(line?.getAttribute('y2'))
  })

  it('renders parallel constraint markers and deletes them on click', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100); document = addPoint(document, 300, 100)
    document = addPoint(document, 100, 200); document = addPoint(document, 300, 200)
    document = addSegment(document, 'P1', 'P2'); document = addSegment(document, 'P3', 'P4')
    document = addConstraint(document, { type: 'parallel', lineA: 'S1', lineB: 'S2' })
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    expect(canvas.querySelectorAll('.geometry-constraint-marker')).toHaveLength(2)
    fireEvent.click(canvas.querySelectorAll('.geometry-constraint-marker')[0])
    expect(canvas.querySelectorAll('.geometry-constraint-marker')).toHaveLength(0)
  })

  it('edits a selected segment length via the inspector', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 300, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    fireEvent.click(canvas.querySelector('line')!)
     fireEvent.click(screen.getByRole('button', { name: '移动' }))
    fireEvent.click(canvas.querySelector('line')!)
    const input = screen.getByLabelText('长度')
    fireEvent.change(input, { target: { value: '3.75' } })
    fireEvent.keyDown(input, { key: 'Enter' })
    const line = canvas.querySelector('line')
     expect(line?.getAttribute('x2')).toBe('250')
  })

  it('draws an arc from center, start, and end clicks', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    fireEvent.click(canvas, { clientX: 200, clientY: 200 })
    fireEvent.click(screen.getByRole('button', { name: '圆弧' }))
    fireEvent.click(canvas.querySelectorAll('circle')[0])
    fireEvent.click(canvas, { clientX: 300, clientY: 200 })
    fireEvent.mouseMove(canvas, { clientX: 300, clientY: 200 })
    expect(canvas.querySelector('.geometry-preview-line')).not.toBeNull()
    fireEvent.mouseMove(canvas, { clientX: 250, clientY: 120 })
    expect(canvas.querySelector('path.geometry-preview-line')).not.toBeNull()
    fireEvent.click(canvas, { clientX: 200, clientY: 300 })
    expect(canvas.querySelector('.geometry-preview-line')).toBeNull()
    expect(canvas.querySelector('path')).not.toBeNull()
  })

  it('moves an arc by dragging its center point', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addArc(document, 'P1', 40, 0, Math.PI / 2)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    const center = canvas.querySelector('circle[r="5"]')!
    fireEvent.mouseDown(center, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 150, clientY: 130 })
    fireEvent.mouseUp(window)
    const movedCenter = canvas.querySelector('circle[r="5"]')!
    expect(movedCenter).toHaveAttribute('cx', '150')
    expect(movedCenter).toHaveAttribute('cy', '130')
    expect(canvas.querySelector('path')?.getAttribute('d')).toContain('190')
    expect(canvas.querySelector('path')?.getAttribute('d')).toContain('130')
  })

  it('moves shared arc endpoints when dragging the arc center', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 150, 100)
    document = addPoint(document, 100, 150)
    document = addSegment(document, 'P1', 'P2')
    document = addArc(document, 'P1', 50, 0, Math.PI / 2, { startAnchor: 'P2', endAnchor: 'P3' })
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    const center = [...canvas.querySelectorAll('circle[r="5"]')].find((point) => point.getAttribute('cx') === '100' && point.getAttribute('cy') === '100')!
    fireEvent.mouseDown(center, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 120, clientY: 130 })
    fireEvent.mouseUp(window)
    const points = [...canvas.querySelectorAll('circle[r="5"]')].map((point) => `${point.getAttribute('cx')},${point.getAttribute('cy')}`)
    expect(points).toContain('170,130')
    expect(points).toContain('120,180')
  })

  it('uses an arc endpoint as the start of a new segment', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addArc(document, 'P1', 50, 0, Math.PI / 2)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    const endpoint = canvas.querySelectorAll('.geometry-handle-endpoint')[0]
    fireEvent.mouseDown(endpoint, { clientX: 150, clientY: 100 })
    fireEvent.click(canvas, { clientX: 220, clientY: 100 })
    const line = canvas.querySelector('line')
    expect(line).toHaveAttribute('x1', '150')
    expect(line).toHaveAttribute('y1', '100')
    expect(line).toHaveAttribute('x2', '220')
    expect(line).toHaveAttribute('y2', '100')
  })

  it('edits arc radius and angles in the inspector', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addArc(document, 'P1', 50, 0, Math.PI / 2)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    fireEvent.click(canvas.querySelector('path')!)
    const radiusInput = screen.getByLabelText('半径')
     fireEvent.change(radiusInput, { target: { value: '2' } })
     expect(canvas.querySelector('path')?.getAttribute('d')).toContain('80')
    const endInput = screen.getByLabelText('终点角')
    fireEvent.change(endInput, { target: { value: '90' } })
    expect(screen.getByLabelText('终点角')).toHaveValue(90)
  })

  it('adjusts arc angles and radius by dragging handles', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addArc(document, 'P1', 50, 0, Math.PI / 2)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    const handles = canvas.querySelectorAll('circle[r="6"]')
    expect(handles).toHaveLength(3)
    fireEvent.mouseDown(handles[0])
    fireEvent.mouseMove(window, { clientX: 100, clientY: 50 })
    fireEvent.mouseUp(window)
    expect(canvas.querySelector('path')?.getAttribute('d')).toContain('100 50')
    const radiusHandle = canvas.querySelectorAll('circle[r="6"]')[2]
    fireEvent.mouseDown(radiusHandle)
    fireEvent.mouseMove(window, { clientX: 180, clientY: 180 })
    fireEvent.mouseUp(window)
    expect(canvas.querySelector('path')?.getAttribute('d')).not.toContain('A 50')
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('applies tangency by selecting a circle and a segment', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addCircle(document, 'P1', 40)
    document = addPoint(document, 300, 40); document = addPoint(document, 400, 40)
    document = addSegment(document, 'P2', 'P3')
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('约束', '相切')
    expect(screen.getByRole('status')).toHaveTextContent('请选择第一个对象（圆 / 圆弧 / 线段）')
    fireEvent.click(canvas, { clientX: 140, clientY: 100 })
    expect(screen.getByRole('status')).toHaveTextContent('请选择第二个对象')
    fireEvent.click(canvas.querySelector('line')!)
    expect(screen.getByRole('button', { name: '选择' })).toHaveClass('active')
  })

  it('mirrors the second point across the axis with the symmetry tool', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 150, 150); document = addPoint(document, 280, 150)
    document = addPoint(document, 200, 100); document = addPoint(document, 200, 300)
    document = addSegment(document, 'P3', 'P4')
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('约束', '对称')
    const points = canvas.querySelectorAll('circle[r="5"]')
    fireEvent.click(points[0])
    fireEvent.click(points[1])
    fireEvent.click(canvas.querySelector('line')!)
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(4)
    expect([...canvas.querySelectorAll('circle[r="5"]')].some((circle) => circle.getAttribute('cx') === '250' && circle.getAttribute('cy') === '150')).toBe(true)
    expect(screen.getByRole('button', { name: '选择' })).toHaveClass('active')
  })

  it('adds a point in the middle of a segment without splitting it', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 300, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    expect(canvas.querySelectorAll('line')).toHaveLength(1)
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(3)
  })

  it('draws and closes a polygon by clicking the first vertex', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    fireEvent.click(canvas, { clientX: 150, clientY: 200 })
    fireEvent.click(canvas.querySelectorAll('circle')[0])
    expect(canvas.querySelectorAll('line')).toHaveLength(3)
  })

  it('selects an entire polygon when clicking inside it', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 300, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 300 })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    fireEvent.click(canvas, { clientX: 200, clientY: 180 })
    expect(screen.getByText('6 个对象')).toBeInTheDocument()
    expect([...canvas.querySelectorAll('line')].filter((line) => line.getAttribute('stroke') === '#cf222e')).toHaveLength(3)
    expect([...canvas.querySelectorAll('circle[r="5"]')].filter((circle) => circle.getAttribute('fill') === '#cf222e')).toHaveLength(3)
  })

  it('moves an entire polygon by dragging its interior', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 300, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 300 })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '移动' }))
    const polygon = canvas.querySelector('polygon')!
    fireEvent.mouseDown(polygon, { clientX: 200, clientY: 180 })
    fireEvent.mouseMove(window, { clientX: 240, clientY: 210 })
    fireEvent.mouseUp(window)
    expect(canvas.querySelector('circle')?.getAttribute('cx')).toBe('140')
    expect(canvas.querySelector('circle')?.getAttribute('cy')).toBe('130')
    expect(canvas.querySelectorAll('line:not(.geometry-constraint-marker)')).toHaveLength(3)
  })

  it('undoes an entire polygon with a single undo', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    fireEvent.click(canvas, { clientX: 150, clientY: 200 })
    fireEvent.click(canvas.querySelectorAll('circle')[0])
    expect(canvas.querySelectorAll('line')).toHaveLength(3)
    fireEvent.click(screen.getByRole('button', { name: '撤销' }))
    expect(canvas.querySelectorAll('line')).toHaveLength(0)
    expect(canvas.querySelectorAll('circle')).toHaveLength(0)
    expect(screen.getByRole('button', { name: '撤销' })).toBeDisabled()
  })

  it('keeps draft polygon edges from intercepting clicks', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    const draftLines = canvas.querySelectorAll('line')
    expect(draftLines).toHaveLength(1)
    expect(draftLines[0].getAttribute('pointer-events')).toBe('none')
    expect(canvas.querySelectorAll('circle[r="7"]')).toHaveLength(0)
    fireEvent.click(canvas, { clientX: 150, clientY: 200 })
    expect(canvas.querySelectorAll('line')).toHaveLength(2)
    fireEvent.keyDown(canvas, { key: 'Enter' })
    expect(canvas.querySelectorAll('line')).toHaveLength(3)
    const finalLine = canvas.querySelectorAll('line')[0]
    expect(finalLine.getAttribute('pointer-events')).toBeNull()
    expect(canvas.querySelectorAll('circle[r="7"]')).toHaveLength(6)
  })

  it('draws connected edges while placing polygon vertices', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    expect(canvas.querySelectorAll('line')).toHaveLength(0)
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    expect(canvas.querySelectorAll('line')).toHaveLength(1)
    fireEvent.click(canvas, { clientX: 150, clientY: 200 })
    expect(canvas.querySelectorAll('line')).toHaveLength(2)
    fireEvent.keyDown(canvas, { key: 'Enter' })
    expect(canvas.querySelectorAll('line')).toHaveLength(3)
    fireEvent.click(screen.getByRole('button', { name: '撤销' }))
    expect(canvas.querySelectorAll('line')).toHaveLength(0)
    expect(screen.getByRole('button', { name: '撤销' })).toBeDisabled()
  })

  it('places polygon vertices across pre-existing segments', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '线段' }))
    fireEvent.click(canvas, { clientX: 200, clientY: 50 })
    fireEvent.click(canvas, { clientX: 200, clientY: 450 })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 150, clientY: 150 })
    fireEvent.click(canvas, { clientX: 200, clientY: 250 })
    fireEvent.click(canvas, { clientX: 120, clientY: 350 })
    expect(canvas.querySelectorAll('line')).toHaveLength(3)
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(5)
    fireEvent.keyDown(canvas, { key: 'Enter' })
    expect(canvas.querySelectorAll('line')).toHaveLength(4)
  })

  it('cancels a polygon draft without creating history', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    expect(canvas.querySelectorAll('circle')).toHaveLength(1)
    fireEvent.keyDown(canvas, { key: 'Escape' })
    expect(canvas.querySelectorAll('circle')).toHaveLength(0)
    expect(screen.getByRole('button', { name: '撤销' })).toBeDisabled()
  })

  it('does not add a point when a construction tool is active', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('约束', '平行')
    fireEvent.click(canvas, { clientX: 120, clientY: 120 })
    expect(canvas.querySelectorAll('circle')).toHaveLength(0)
  })

  it('blocks polygon vertex drags that would self-cross the shape', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    ;[[100, 100], [500, 100], [500, 500], [100, 500]].forEach(([x, y]) => fireEvent.click(canvas, { clientX: x, clientY: y }))
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    fireEvent.click(canvas.querySelectorAll('circle[r="5"]')[0], { clientX: 100, clientY: 100 })
    expect(canvas.querySelectorAll('line')).toHaveLength(4)
    const target = canvas.querySelectorAll('circle[r="5"]')[1]
    fireEvent.mouseDown(target, { clientX: 500, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: -200, clientY: 100 })
    fireEvent.mouseUp(window)
    const dragged = canvas.querySelectorAll('circle[r="5"]')[1]
    expect(Number(dragged.getAttribute('cx'))).toBeGreaterThan(50)
    expect(canvas.querySelectorAll('line')).toHaveLength(4)
  })

  it('keeps drag edits undoable', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    const point = canvas.querySelector('circle')
    fireEvent.mouseDown(point!, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 180, clientY: 180 })
    fireEvent.mouseUp(window)
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('translates a whole segment with the move tool', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100); document = addPoint(document, 300, 100)
    document = addSegment(document, 'P1', 'P2')
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '移动' }))
    fireEvent.mouseDown(canvas.querySelector('line')!, { clientX: 200, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 250, clientY: 130 })
    fireEvent.mouseUp(window)
    const line = canvas.querySelector('line')
    expect(line?.getAttribute('x1')).toBe('150')
    expect(line?.getAttribute('y1')).toBe('130')
    expect(line?.getAttribute('x2')).toBe('350')
    expect(line?.getAttribute('y2')).toBe('130')
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('moves a midpoint constraint with the dragged segment', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 300, 100)
    document = addSegment(document, 'P1', 'P2')
    document = addPoint(document, 200, 100)
    document = addConstraint(document, { type: 'midpoint', point: 'P3', line: 'S1' })
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '移动' }))
    fireEvent.mouseDown(canvas.querySelector('line')!, { clientX: 200, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 250, clientY: 140 })
    fireEvent.mouseUp(window)
    const midpoint = [...canvas.querySelectorAll('circle[r="5"]')][2]
    expect(midpoint.getAttribute('cx')).toBe('250')
    expect(midpoint.getAttribute('cy')).toBe('140')
  })

  it('does not allow a midpoint constraint point to be dragged directly', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 300, 100)
    document = addSegment(document, 'P1', 'P2')
    document = addPoint(document, 200, 100)
    document = addConstraint(document, { type: 'midpoint', point: 'P3', line: 'S1' })
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    const midpoint = [...canvas.querySelectorAll('circle[r="5"]')][2]
    fireEvent.mouseDown(midpoint, { clientX: 200, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 260, clientY: 150 })
    fireEvent.mouseUp(window)
    const unchanged = [...canvas.querySelectorAll('circle[r="5"]')][2]
    expect(unchanged.getAttribute('cx')).toBe('200')
    expect(unchanged.getAttribute('cy')).toBe('100')
  })

  it('keeps a point on a segment while allowing it to slide along the segment', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 300, 100)
    document = addSegment(document, 'P1', 'P2')
    document = addPoint(document, 180, 100)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    const point = [...canvas.querySelectorAll('circle[r="5"]')][2]
    fireEvent.mouseDown(point, { clientX: 180, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 260, clientY: 150 })
    fireEvent.mouseUp(window)
    const moved = [...canvas.querySelectorAll('circle[r="5"]')][2]
    expect(moved.getAttribute('cx')).toBe('260')
    expect(moved.getAttribute('cy')).toBe('100')
    fireEvent.click(screen.getByRole('button', { name: '移动' }))
    fireEvent.mouseDown(canvas.querySelector('line')!, { clientX: 200, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 250, clientY: 130 })
    fireEvent.mouseUp(window)
    const followed = [...canvas.querySelectorAll('circle[r="5"]')][2]
    expect(followed.getAttribute('cx')).toBe('310')
    expect(followed.getAttribute('cy')).toBe('130')
  })

  it('keeps an attached point in place when resizing its host edge', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 300, 100)
    document = addSegment(document, 'P1', 'P2')
    document = addPoint(document, 200, 100)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    fireEvent.click(canvas.querySelector('line')!)
    const length = screen.getByLabelText('长度')
    fireEvent.change(length, { target: { value: '7.5' } })
    fireEvent.keyDown(length, { key: 'Enter' })
    const attached = [...canvas.querySelectorAll('circle[r="5"]')][2]
    expect(attached.getAttribute('cx')).toBe('250')
    expect(attached.getAttribute('cy')).toBe('100')
  })

  it('moves a circle by dragging its stroke with the move tool', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addCircle(document, 'P1', 40)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '移动' }))
    fireEvent.mouseDown(canvas.querySelector('circle[r="40"]')!, { clientX: 140, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 160, clientY: 110 })
    fireEvent.mouseUp(window)
    const center = [...canvas.querySelectorAll('circle[r="5"]')][0]
    expect(center.getAttribute('cx')).toBe('120')
    expect(center.getAttribute('cy')).toBe('110')
  })

  it('inserts a constrained midpoint into a segment', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 300, 100)
    document = addSegment(document, 'P1', 'P2')
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    clickCategoryTool('构造', '中点')
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    expect(canvas.querySelectorAll('line:not(.geometry-constraint-marker)')).toHaveLength(1)
    expect([...canvas.querySelectorAll('circle[r="5"]')].some((point) => point.getAttribute('cx') === '200' && point.getAttribute('cy') === '100')).toBe(true)
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    fireEvent.click(canvas.querySelectorAll('circle[r="5"]')[2])
    expect(screen.getByText(/P3 = mid\(P1-P2\)/)).toBeInTheDocument()
  })

  it('constructs a midpoint when the segment itself is clicked', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addPoint(document, 300, 100)
    document = addSegment(document, 'P1', 'P2')
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    clickCategoryTool('构造', '中点')
    fireEvent.click(screen.getByRole('img', { name: '几何图画布' }).querySelector('line')!, { clientX: 200, clientY: 100 })
    expect(screen.getByRole('img', { name: '几何图画布' }).querySelectorAll('circle[r="5"]')).toHaveLength(3)
    expect(screen.getByRole('img', { name: '几何图画布' }).querySelectorAll('line')).toHaveLength(1)
  })

  it('adjusts the selected circle radius with arrow keys', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('option', { name: '圆' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 180, clientY: 100 })
    fireEvent.mouseUp(canvas, { clientX: 180, clientY: 100 })
    const circle = canvas.querySelector('circle[r="40"]')
    expect(circle).not.toBeNull()
    fireEvent.click(circle!)
    fireEvent.keyDown(canvas, { key: 'ArrowUp' })
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('does not create a second circle when dragging the radius handle', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addCircle(document, 'P1', 40)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    const handle = canvas.querySelector('circle[data-handle][r="6"]')
    expect(handle).not.toBeNull()
    const circleCount = () => canvas.querySelectorAll('circle:not([data-handle]):not([r="5"]):not(.geometry-snap-halo)').length
    expect(circleCount()).toBe(1)
    fireEvent.mouseDown(handle!, { clientX: 140, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 160, clientY: 120 })
    fireEvent.mouseUp(window)
    fireEvent.click(handle!, { clientX: 160, clientY: 120 })
    expect(circleCount()).toBe(1)
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(1)
  })

  it('keeps drag edits undoable', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    const point = canvas.querySelector('circle')
    fireEvent.mouseDown(point!, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 180, clientY: 180 })
    fireEvent.mouseUp(window)
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('draws a square by dragging with the shape tool', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('option', { name: '正方形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 260 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 260 })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    fireEvent.click(canvas.querySelectorAll('circle[r="5"]')[0])
    expect(canvas.querySelectorAll('line:not(.geometry-constraint-marker)')).toHaveLength(4)
    const constraintLabels = [...document.querySelectorAll('.geometry-constraints span')].map((element) => element.textContent ?? '')
    expect(constraintLabels.some((label) => label.includes('平行'))).toBe(true)
    expect(constraintLabels.some((label) => label.includes('等长'))).toBe(true)
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('does not start a new shape when pressing near an existing shape', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('option', { name: '正方形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 160 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 160 })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    expect(canvas.querySelectorAll('line:not(.geometry-constraint-marker)')).toHaveLength(4)
    fireEvent.mouseDown(canvas, { clientX: 306, clientY: 306 })
    fireEvent.mouseMove(window, { clientX: 380, clientY: 380 })
    fireEvent.mouseUp(window)
    expect(canvas.querySelectorAll('line:not(.geometry-constraint-marker)')).toHaveLength(4)
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(4)
  })

  it('stretches a rectangle from one edge while keeping the opposite edge fixed', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('option', { name: '矩形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 180 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 180 })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    const edge = canvas.querySelectorAll('line:not(.geometry-constraint-marker)')[0]
    fireEvent.mouseDown(edge!, { clientX: 200, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 230, clientY: 120 })
    fireEvent.mouseUp(window)
    const points = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => ({ cx: Number(circle.getAttribute('cx')), cy: Number(circle.getAttribute('cy')) }))
    expect(points).toEqual([
      { cx: 100, cy: 120 },
      { cx: 300, cy: 120 },
      { cx: 300, cy: 180 },
      { cx: 100, cy: 180 }
    ])
  })

  it('rotates a right triangle when dragging a vertex', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('option', { name: '直角三角形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 260 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 260 })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    const vertices = canvas.querySelectorAll('circle[r="5"]')
    fireEvent.mouseDown(vertices[1], { clientX: 300, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 360, clientY: 100 })
    fireEvent.mouseUp(window)
    const movedVertices = [...canvas.querySelectorAll('circle[r="5"]')]
    expect(movedVertices.map((vertex) => `${vertex.getAttribute('cx')},${vertex.getAttribute('cy')}`)).not.toEqual(['100,100', '360,100', '100,260'])
    expect(movedVertices).toHaveLength(3)
  })

  it('keeps the right angle when dragging a right triangle hypotenuse', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('option', { name: '直角三角形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 260 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 260 })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    const hypotenuse = canvas.querySelectorAll('line:not(.geometry-constraint-marker)')[1]
    fireEvent.mouseDown(hypotenuse, { clientX: 200, clientY: 180 })
    fireEvent.mouseMove(window, { clientX: 240, clientY: 220 })
    fireEvent.mouseUp(window)
    const points = [...canvas.querySelectorAll('circle[r="5"]')].map((point) => ({ x: Number(point.getAttribute('cx')), y: Number(point.getAttribute('cy')) }))
    const rightAngle = points.some((right, index) => {
      const other = points.filter((_point, pointIndex) => pointIndex !== index)
      return Math.abs((other[0].x - right.x) * (other[1].x - right.x) + (other[0].y - right.y) * (other[1].y - right.y)) < 1e-5
    })
    expect(rightAngle).toBe(true)
  })

  it('moves a selected right triangle as a complete shape', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('option', { name: '直角三角形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 260 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 260 })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    const polygon = canvas.querySelector('polygon')!
    fireEvent.mouseDown(polygon, { clientX: 160, clientY: 130 })
    fireEvent.mouseMove(window, { clientX: 200, clientY: 170 })
    fireEvent.mouseUp(window)
    expect(canvas.querySelectorAll('circle[r="5"]')[0]).toHaveAttribute('cx', '140')
    expect(canvas.querySelectorAll('circle[r="5"]')[0]).toHaveAttribute('cy', '140')
  })

  it('edits the interior angle of a parallelogram vertex from the side panel', async () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('option', { name: '平行四边形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 300 })
    fireEvent.mouseMove(window, { clientX: 400, clientY: 200 })
    fireEvent.mouseUp(canvas, { clientX: 400, clientY: 200 })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    const vertices = canvas.querySelectorAll('circle[r="5"]')
    const p2 = vertices[1]
    const px = Number(p2.getAttribute('cx'))
    const py = Number(p2.getAttribute('cy'))
    fireEvent.mouseDown(p2, { clientX: px, clientY: py })
    fireEvent.mouseUp(window)
    const input = await screen.findByLabelText('内角')
    expect(Number((input as HTMLInputElement).value)).toBeGreaterThan(90)
    const before = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => `${circle.getAttribute('cx')},${circle.getAttribute('cy')}`)
    fireEvent.change(input, { target: { value: '95' } })
    fireEvent.keyDown(input, { key: 'Enter' })
    await waitFor(() => {
      expect(document.querySelector('.geometry-constraints')?.textContent).toContain('角度')
    })
    const after = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => `${circle.getAttribute('cx')},${circle.getAttribute('cy')}`)
    expect(after).not.toEqual(before)
  })

  it('selects any segment with the select tool and shows its editable length', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('option', { name: '正方形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 160 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 160 })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    const edge = canvas.querySelectorAll('line:not(.geometry-constraint-marker)')[0]
    fireEvent.click(edge!, { clientX: 200, clientY: 100 })
    expect(screen.getByText('类型: segment')).toBeInTheDocument()
    expect(screen.getByLabelText('长度')).not.toBeNull()
    // 点击边不再穿透创建新点
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(4)
  })

  it('edits circle radius from the selected center point', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addCircle(document, 'P1', 40)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.mouseDown(canvas.querySelector('circle[r="5"]')!, { clientX: 100, clientY: 100 })
    fireEvent.mouseUp(window)
    const radiusInput = screen.getByLabelText('半径')
    fireEvent.change(radiusInput, { target: { value: '60' } })
    expect(canvas.querySelector('circle[r="60"]')).not.toBeNull()
  })

  it('drags a circle by its center point', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addCircle(document, 'P1', 40)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    const center = canvas.querySelector('.geometry-handle-center')!
    fireEvent.mouseDown(center, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 160, clientY: 140 })
    fireEvent.mouseUp(window)
    const movedCenter = canvas.querySelector('.geometry-handle-center')!
    const movedCircle = canvas.querySelector('circle[r="40"]')!
    expect(movedCenter).toHaveAttribute('cx', '160')
    expect(movedCenter).toHaveAttribute('cy', '140')
    expect(movedCircle).toHaveAttribute('cx', '160')
    expect(movedCircle).toHaveAttribute('cy', '140')
  })

  it('keeps a ring point on the circumference when editing the radius from it', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 100)
    document = addCircle(document, 'P1', 40)
    document = addPoint(document, 140, 100)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    const ringPoint = [...canvas.querySelectorAll('circle[r="5"]')][1]
    fireEvent.mouseDown(ringPoint, { clientX: 140, clientY: 100 })
    fireEvent.mouseUp(window)
    const radiusInput = screen.getByLabelText('半径')
    fireEvent.change(radiusInput, { target: { value: '80' } })
    expect(canvas.querySelector('circle[r="80"]')).not.toBeNull()
    const moved = [...canvas.querySelectorAll('circle[r="5"]')][1]
    expect(moved.getAttribute('cx')).toBe('180')
    expect(moved.getAttribute('cy')).toBe('100')
  })

  it('shows an editable interior angle for free triangle vertices', async () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '多边形' }))
    ;[[150, 150], [350, 150], [250, 320]].forEach(([x, y]) => fireEvent.click(canvas, { clientX: x, clientY: y }))
    fireEvent.click(canvas, { clientX: 150, clientY: 150 })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    const vertex = canvas.querySelectorAll('circle[r="5"]')[0]
    fireEvent.mouseDown(vertex, { clientX: 150, clientY: 150 })
    fireEvent.mouseUp(window)
    const input = await screen.findByLabelText('内角')
    expect(Number((input as HTMLInputElement).value)).toBeGreaterThan(30)
    const before = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => `${circle.getAttribute('cx')},${circle.getAttribute('cy')}`)
    fireEvent.change(input, { target: { value: '80' } })
    fireEvent.keyDown(input, { key: 'Enter' })
    await waitFor(() => {
      const after = [...canvas.querySelectorAll('circle[r="5"]')].map((circle) => `${circle.getAttribute('cx')},${circle.getAttribute('cy')}`)
      expect(after).not.toEqual(before)
    })
  })

  it('shows rectangle corner angles as read-only 90 degrees', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('option', { name: '矩形' }))
    fireEvent.mouseDown(canvas, { clientX: 100, clientY: 100 })
    fireEvent.mouseMove(window, { clientX: 300, clientY: 180 })
    fireEvent.mouseUp(canvas, { clientX: 300, clientY: 180 })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    const vertex = canvas.querySelectorAll('circle[r="5"]')[0]
    fireEvent.mouseDown(vertex, { clientX: 100, clientY: 100 })
    fireEvent.mouseUp(window)
    expect(screen.getByText(/内角: 90°/)).toBeInTheDocument()
    expect(screen.queryByLabelText('内角')).toBeNull()
  })

  it('shows editable point coordinates in the inspector', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    expect(screen.getByLabelText('X')).toHaveValue(100)
    fireEvent.change(screen.getByLabelText('X'), { target: { value: '140' } })
    expect(screen.getByLabelText('X')).toHaveValue(140)
  })

  it('creates an angle constraint from three points and edits its value', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    ;[[200, 200], [300, 200], [350, 150]].forEach(([x, y]) => { fireEvent.click(screen.getByRole('button', { name: '点' })); fireEvent.click(canvas, { clientX: x, clientY: y }) })
    clickCategoryTool('约束', '角度')
    const points = [...canvas.querySelectorAll('circle[r="5"]')]
    fireEvent.click(points[0])
    fireEvent.click(points[1])
    fireEvent.click(points[2])
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    fireEvent.click(points[1])
    expect(screen.getByText(/∠P1P2P3 = 135°/, { selector: '.geometry-constraint-detail' })).toBeInTheDocument()
    const input = screen.getByLabelText('角度-0')
    expect(input).toHaveValue(135)
    fireEvent.change(input, { target: { value: '90' } })
    const armB = [...canvas.querySelectorAll('circle[r="5"]')][2]
    expect(Number(armB.getAttribute('cx'))).toBeCloseTo(300, 5)
    expect(Number(armB.getAttribute('cy'))).toBeCloseTo(200 - Math.hypot(50, 50), 5)
  })

  it('renames a selected point and shows the label on canvas', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.change(screen.getByLabelText('名称'), { target: { value: 'A' } })
    expect(screen.getByLabelText('名称')).toHaveValue('A')
    expect(canvas.textContent).toContain('A')
    expect(screen.getAllByText('A').length).toBeGreaterThan(0)
  })

  it('selects points inside a dragged rectangle', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '点' })); fireEvent.click(canvas, { clientX: 100, clientY: 100 })
    fireEvent.click(screen.getByRole('button', { name: '点' })); fireEvent.click(canvas, { clientX: 200, clientY: 200 })
    fireEvent.mouseDown(canvas, { clientX: 70, clientY: 70 })
    fireEvent.mouseMove(window, { clientX: 230, clientY: 230 })
    fireEvent.mouseUp(window)
    expect(screen.getByText('2 个对象')).toBeInTheDocument()
  })

  it('creates an ellipse by selecting two foci and dragging from the second focus', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('option', { name: '椭圆' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 200 })
    fireEvent.click(canvas, { clientX: 200, clientY: 200 })
    const focus = canvas.querySelectorAll('circle[r="5"]')[1]
    fireEvent.mouseDown(focus, { clientX: 200, clientY: 200 })
    fireEvent.mouseMove(window, { clientX: 200, clientY: 350 })
    fireEvent.mouseUp(window)
    const ellipse = canvas.querySelector('ellipse:not(.geometry-preview-line)')
    expect(ellipse).not.toBeNull()
    expect(Number(ellipse!.getAttribute('rx'))).toBeGreaterThan(100)
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(2)
  })

  it('shows ellipse properties when the ellipse is selected', () => {
    let document = addPoint(createGeometryDocument(), 100, 200)
    document = addPoint(document, 200, 200)
    document = addEllipse(document, 'P1', 'P2', 140)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '选择' }))
    fireEvent.click(canvas.querySelector('ellipse')!)
    expect(screen.getByText('类型: ellipse')).toBeInTheDocument()
    expect(screen.getByLabelText('半长轴')).toHaveValue(3.5)
    fireEvent.change(screen.getByLabelText('半长轴'), { target: { value: '4' } })
    expect(canvas.querySelector('ellipse')).toHaveAttribute('rx', '160')
  })

  it('resizes an ellipse by dragging its major-axis handle', () => {
    let document = addPoint(createGeometryDocument(), 100, 200)
    document = addPoint(document, 200, 200)
    document = addEllipse(document, 'P1', 'P2', 140)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    const handle = canvas.querySelector('circle[data-handle]')!
    fireEvent.mouseDown(handle, { clientX: 290, clientY: 200 })
    fireEvent.mouseMove(window, { clientX: 330, clientY: 200 })
    fireEvent.mouseUp(window)
    expect(canvas.querySelector('ellipse')).toHaveAttribute('rx', '180')
    expect(screen.getByRole('button', { name: '撤销' })).not.toBeDisabled()
  })

  it('creates an ellipse with three clicks', () => {
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('option', { name: '椭圆' }))
    fireEvent.click(canvas, { clientX: 100, clientY: 200 })
    fireEvent.click(canvas, { clientX: 300, clientY: 200 })
    fireEvent.click(canvas, { clientX: 200, clientY: 100 })
    expect(canvas.querySelector('ellipse')).not.toBeNull()
    expect(screen.getByRole('button', { name: '选择' })).toHaveClass('active')
  })

  it('adds points on circle, arc, and ellipse edges', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 200, 200)
    document = addCircle(document, 'P1', 60)
    document = addArc(document, 'P1', 80, 0, Math.PI / 2)
    document = addPoint(document, 100, 400)
    document = addPoint(document, 200, 400)
    document = addEllipse(document, 'P2', 'P3', 80)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    const pointTool = screen.getByRole('button', { name: '点' })
    fireEvent.click(pointTool)
    fireEvent.click(canvas.querySelector('circle[r="60"]')!, { clientX: 260, clientY: 200 })
    fireEvent.click(pointTool)
    fireEvent.click(canvas.querySelector('path:not(.geometry-hit-area)')!, { clientX: 280, clientY: 200 })
    fireEvent.click(pointTool)
    fireEvent.click(canvas.querySelector('ellipse')!, { clientX: 200, clientY: 320 })
    expect(canvas.querySelectorAll('circle[r="5"]')).toHaveLength(5)
  })

  it('keeps a point added on an arc constrained to the arc while dragging', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 200, 200)
    document = addArc(document, 'P1', 80, 0, Math.PI / 2)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    fireEvent.click(canvas.querySelector('path:not(.geometry-hit-area)')!, { clientX: 280, clientY: 200 })
    expect(screen.getByRole('button', { name: '选择' })).toHaveClass('active')
    const point = [...canvas.querySelectorAll('circle[r="5"]')][1]
    fireEvent.mouseDown(point, { clientX: 280, clientY: 200 })
    fireEvent.mouseMove(window, { clientX: 200, clientY: 280 })
    fireEvent.mouseUp(window)
    const moved = [...canvas.querySelectorAll('circle[r="5"]')][1]
    const dx = Number(moved.getAttribute('cx')) - 200
    const dy = Number(moved.getAttribute('cy')) - 200
    expect(Math.hypot(dx, dy)).toBeCloseTo(80, 5)
  })

  it('keeps a point added on a circle constrained while dragging', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 200, 200)
    document = addCircle(document, 'P1', 80)
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    fireEvent.click(screen.getByRole('button', { name: '点' }))
    fireEvent.click(canvas.querySelector('circle[r="80"]')!, { clientX: 280, clientY: 200 })
    const circlePoint = canvas.querySelector('[data-attachment-kind="circle"]')!
    fireEvent.mouseDown(circlePoint, { clientX: 280, clientY: 200 })
    fireEvent.mouseMove(window, { clientX: 200, clientY: 280 })
    fireEvent.mouseUp(window)
    const moved = canvas.querySelector('[data-attachment-kind="circle"]')!
    expect(Math.hypot(Number(moved.getAttribute('cx')) - 200, Number(moved.getAttribute('cy')) - 200)).toBeCloseTo(80, 5)
  })

  it('keeps a point added on an ellipse constrained while dragging', () => {
    let document = createGeometryDocument()
    document = addPoint(document, 100, 400)
    document = addPoint(document, 200, 400)
    document = addEllipse(document, 'P1', 'P2', 80)
    document = addPoint(document, 150, 269.2330316937798)
    document = { ...document, points: document.points.map((point) => point.id === 'P3' ? { ...point, role: 'attachment', attachment: { objectId: 'E1', kind: 'ellipse' as const, parameter: -Math.PI / 2 } } : point) }
    render(<GeometryEditorDialog onClose={vi.fn()} onSave={vi.fn()} initialDocument={document} />)
    const canvas = screen.getByRole('img', { name: '几何图画布' })
    const point = canvas.querySelector('[data-attachment-kind="ellipse"]')!
    fireEvent.mouseDown(point, { clientX: 150, clientY: 269.2330316937798 })
    fireEvent.mouseMove(window, { clientX: 100, clientY: 400 })
    fireEvent.mouseUp(window)
    expect(Number(canvas.querySelector('[data-attachment-kind="ellipse"]')!.getAttribute('cx'))).not.toBe(200)
  })
})
