export const IpcChannels = {
  appConfigGet: 'config:get',
  appConfigSet: 'config:set',
  helpOpen: 'help:open',
  windowSetTitle: 'window:set-title',
  windowSetDirty: 'window:set-dirty',
  windowSetLanguage: 'window:set-language',
  menuCommand: 'menu:command',
  menuOpenRecent: 'menu:open-recent',
  fileOpenRecentFolder: 'file:open-recent-folder',
  dialogOpenFile: 'dialog:open-file',
  dialogOpenImage: 'dialog:open-image',
  dialogOpenDirectory: 'dialog:open-directory',
  dialogSaveFile: 'dialog:save-file',
  fileRead: 'file:read',
  fileOpenRecent: 'file:open-recent',
  recentList: 'recent:list',
  recentAdd: 'recent:add',
  recentAddFolder: 'recent:add-folder',
  recentRemove: 'recent:remove',
  recentRemoveFolder: 'recent:remove-folder',
  recentClear: 'recent:clear',
  fileWrite: 'file:write',
  fileImportImage: 'file:import-image',
  fileSaveImageBlob: 'file:save-image-blob',
  filePrepareImages: 'file:prepare-images',
  dirScan: 'dir:scan',
  dirScanCancel: 'dir:scan-cancel',

  exportHtml: 'export:html',
  exportPdf: 'export:pdf',
  mediaAllow: 'media:allow'
} as const

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels]
